
    <footer>
        <div id="Contact">
            <p>Contact us at:</p>
            <a href="mailto:enablesolutions@official.com.au">enablesolutions@official.com.au</a>
        </div>
        <div class="ftr-nav">
            <nav class="ftr-elements">
            <a class="linkf" href="index.php">Home</a>
            <a class="linkf" href="about.php">About</a>
            <a class="linkf" href="jobs.php">Jobs</a>
            <a class="linkf" href="apply.php">Apply</a>
            <a class="linkf" href="manage.php">Manage</a>
            <a class="linkf" href="enhancements.php">Enhancements</a>
            </nav>
        </div>
        <div id="Author">
            <p>Author: &#169; Enable Solutions</p>
            <p>Last Edited: October 2024</p>
        </div>
    </footer>
