
    <head>
        <meta charset="UTF-8" />
        <meta name="author" content="Riley Parry" />
        <meta name="description" content="header code." />
        <meta
            name="keywords"
            content="header, enable solutions, cybersecurity"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link href="styles/style.css" rel="stylesheet" />
        <title>Header</title>
    </head>
    <body>
        <header>
            <h1>Enable Solutions</h1>
            <section class="p-menu">
                <nav id="navbar" class="navigation" role="navigation">
                    <input id="toggle" type="checkbox" />
                    <label class="hamburger" for="toggle">
                        <div class="top"></div>
                        <div class="meat"></div>
                        <div class="bottom"></div>
                    </label>

                    <nav class="menu">
                        <a class="linkh" href="index.php">Home</a>
                        <a class="linkh" href="about.php">About</a>
                        <a class="linkh" href="jobs.php">Jobs</a>
                        <a class="linkh" href="apply.php">Apply</a>
                        <a class="linkh" href="manage.php">Manage</a>
                        <a class="linkh" href="enhancements.php"
                            >Enhancements</a
                        >
                        <a
                            class="lin kbutton-nav"
                            href="mailto:enablesolutions@official.com.au"
                            >Contact</a
                        >
                    </nav>
                </nav>
            </section>
        </header>
    </body>
</html>
